export { default as Dashboard } from './Dashboard'
export { default as Products } from './Products'
export { default as Categories } from './Categories'
export { default as Sales } from './Sales'
export { default as Users } from './Users'
export { default as Stock } from './Stock'
