// Client pages exports
export { default as Home } from './Home'
export { default as Catalog } from './Catalog'
export { default as ProductDetail } from './ProductDetail'
export { default as Cart } from './Cart'
export { default as Checkout } from './Checkout'
export { default as Orders } from './Orders'
export { default as OrderDetail } from './OrderDetail'
export { default as Profile } from './Profile'
export { default as Loyalty } from './Loyalty'
